name: Release Docker Image

on:
  workflow_dispatch: # for manual testing
    inputs:
      runs_on:
        description: "Runs on"
        default: self-hosted
        required: false
        type: string
      warp_build_profile:
        description: "WarpBuild profile to build with"
        default: ""
        required: false
        type: string
      platforms:
        description: "Platforms to build for"
        default: linux/amd64
        required: false
        type: string
  push:
    # Publish semver tags as releases:
    tags: ["*.*.*"]

jobs:
  call-docker-release:
    permissions:
      contents: write
      packages: write
    uses: thealtoclef/modular-automations/.github/workflows/docker-release.yaml@main
    with:
      runs_on: ${{ github.event.inputs.runs_on || 'self-hosted' }}
      warp_build_profile: ${{ github.event.inputs.warp_build_profile || '' }}
      platforms: ${{ github.event.inputs.profiles || 'linux/amd64' }}
      force_build: true
