name: Release Helm Chart

on:
  workflow_dispatch: # for manual testing
  push:
    branches:
      - main
    paths:
      - "**/Chart.yaml"

jobs:
  call-helm-release:
    permissions:
      contents: write
      packages: write
    uses: thealtoclef/modular-automations/.github/workflows/helm-release.yaml@main
    with:
      chart_dirs: "helm-charts/charts"
